Add screen home
JiggyDevs/twikkl-app pull request #19
Opened 2023-05-23 21:11 UTC by Vcky4

This pull request adds a new screen home and a component VideoFeedItem to the application, enhancing the user experience and providing a valuable feature. 
The screen home has a vertical swipeable list of videos(VideoFeedItem) and layout components that are intuitive and visually appealing. I have thoroughly reviewed the code changes, and everything appears to be in order. 

The following has not been done yet
1. manually pause the video on tap

Please review and merge at your convenience. Thank you!

2023-05-26 09:06 UTC, Vcky4 commented on app/Home.tsx
> +  ]
I've fix this in the next PR

2023-05-26 09:06 UTC, Vcky4 commented on app/Home.tsx
> + * TODO - Build Home screen component
Fixed too

2023-05-26 09:07 UTC, Vcky4 commented on app/Home.tsx
> +      <FlatList
We can't use ScrollView as users will post thousands of videos and we can't go back to change it to Flatlist then

2023-05-26 09:08 UTC, Vcky4 commented on app/Home.tsx
> +        keyExtractor={(item, index) => index.toString()}
There's no real data for now hence me using an index

When we have real data I'll change it to Id

If you observed both index and item is there which makes it easier to switch

2023-05-26 09:26 UTC, Vcky4 commented on src/components/VideoFeedItem.tsx
> +        justifyContent: "flex-end",
done

2023-05-26 09:33 UTC, Vcky4 commented on src/components/VideoFeedItem.tsx
> +          <TouchableOpacity style={{
I changed my mind

2023-05-26 10:16 UTC, Vcky4 commented
Video pause and play has been done

2023-05-27 07:48 UTC, firasrg requested changes

2023-05-27 07:48 UTC, firasrg commented on assets/videos/girl.mp4
Can you please compress this video to reduce it's size to something inferior than 7.56 MB?

2023-05-27 07:48 UTC, firasrg commented on src/components/VideoFeedItem.tsx
> + */
This is a wrong comment!

2023-05-27 07:48 UTC, firasrg commented on src/components/VideoFeedItem.tsx
> +  }
I think that, **it's recommended** to follow the Imprative playback APIs when controlling videos state.  
Please follow [the guide's example](https://docs.expo.dev/versions/latest/sdk/video/#usage). 

There are some **useful methods** in Video components that can be used to play/pause.

2023-05-27 07:48 UTC, firasrg commented on src/components/VideoFeedItem.tsx
> +      style={{ flex: 1 }}>
Why I still see style declarations thrown into component?

2023-05-27 07:48 UTC, firasrg commented on src/components/VideoFeedItem.tsx
> +                    }}>
Same note for styles.

2023-05-27 07:48 UTC, firasrg commented on src/components/VideoFeedItem.tsx
> +            }}>
Same note for styles, and please consider using our **variants**.

2023-05-27 07:48 UTC, firasrg commented on src/components/VideoFeedItem.tsx
> +              marginTop: 14,
Same note for styles.

2023-05-27 07:48 UTC, firasrg commented on src/components/VideoFeedItem.tsx
> +            <View style={{
Same note for styles

2023-05-27 07:48 UTC, firasrg commented on src/components/VideoFeedItem.tsx
> +            <TouchableOpacity >
Please add `<TouchableOpacity >` inside `ButtonAddSimple` component, as it's button, so It has to be touchable.

2023-05-27 08:01 UTC, firasrg commented
Recap Review Feedback: Code Organization, Commit History, and Documentation

@Vcky4 I've completed my review of the pull request and would like to provide some general feedback regarding the code organization, commit history, and adherence to the README and CONTRIBUTING guide.

### Code Organization:
It appears that the code could benefit from better organization and structure. For example, the styles. I'd like to see the use of variants. The styles must be declared separately, unless there is a reason to declare them into the components. Modularity makes it easier for other developers to understand the codebase.

### Commit History:
I noticed that there are a significant number of commits in this pull request (13 in total) and I assume more after my recent review. While it's not inherently bad to have multiple commits, it would be beneficial to group related changes together. This helps provide a clearer and more concise overview of the changes made. Consider **squashing** some commits that address similar functionality or bug fixes.

### README and CONTRIBUTING Guide:
Please make sure to follow the guidelines outlined in the README and CONTRIBUTING guide. These documents serve as **essential** references for developers. Adhering to the guidelines ensures consistency across the codebase and helps streamline the development process. Take some time to review and update your code accordingly.

Remember, we strive for a well-structured and maintainable codebase, so taking these considerations into account will contribute to the overall quality of the project.

Feel free to reach out if you have any questions or require further clarification on any of the points mentioned above.

Best regards,

2023-05-27 20:57 UTC, merged